Add rest

diff --git a/tools/pipelines/test-perf-benchmarks.yml b/tools/pipelines/test-perf-benchmarks.yml
--- a/tools/pipelines/test-perf-benchmarks.yml
+++ b/tools/pipelines/test-perf-benchmarks.yml
@@ -430,3 +430,179 @@ stages:
               # allowPartiallySucceededBuilds: true # No effect as long as we have buildVersionToDownload: specific
               # branchName: $(Build.SourceBranch)   # No effect as long as we have buildVersionToDownload: specific
 
+          # Install e2e test package
+          - task: Bash@3
+            displayName: Install Test Package
+            inputs:
+              targetType: 'inline'
+              workingDirectory: ${{ variables.testWorkspace }}
+              script: |
+                echo "Install ${{ variables.testPackage }}"
+                TEST_PACKAGE_FILE_PATTERN=${{ variables.escapedTestPackage }}-?.?.?-*.tgz
+                TEST_PACKAGE_PATH_PATTERN=$(Pipeline.Workspace)/client/pack/scoped/$TEST_PACKAGE_FILE_PATTERN
+
+                echo $TEST_PACKAGE_FILE_PATTERN
+                echo $TEST_PACKAGE_PATH_PATTERN
+
+                echo `ls -1 $TEST_PACKAGE_PATH_PATTERN | wc -l`
+                echo `ls $TEST_PACKAGE_PATH_PATTERN`
+
+                if [[ `ls -1 $TEST_PACKAGE_PATH_PATTERN | wc -l` -eq 1 ]]; then
+                  TEST_PACKAGE_TGZ=`ls $TEST_PACKAGE_PATH_PATTERN`
+                else
+                  ls -1 $TEST_PACKAGE_PATH_PATTERN
+                  echo "##vso[task.logissue type=error]Test package '${{ variables.testPackage }}' not found, or there are more then one found"
+                  exit -1
+                fi
+
+                npm install $TEST_PACKAGE_TGZ
+
+          - task: Bash@3
+            displayName: Prepare test package to run tests
+            inputs:
+              targetType: 'inline'
+              workingDirectory: ${{ variables.testWorkspace }}/node_modules/${{ variables.testPackage }}
+              script: |
+                cp ${{ variables.testWorkspace }}/.npmrc . ;
+                npm i ;
+
+          # We run both types of tests in the same bash step so we can make sure to run the second set even if the first
+          # one fails.
+          # Doing this with separate ADO steps is not easy.
+          # This step reports failure if either of the test runs reports failure.
+          - task: Bash@3
+            displayName: Run tests ${{ stage }}
+            inputs:
+              targetType: 'inline'
+              workingDirectory: ${{ variables.testWorkspace }}/node_modules/${{ variables.testPackage }}
+              script: |
+
+                # Run execution time tests
+                echo "FLUID_ENDPOINTNAME = $FLUID_ENDPOINTNAME"
+                if [[ $stage -eq 'local' ]]; then
+                npm run test:benchmark:report;
+                fi
+                if [[ $stage -eq 'odsp' ]]; then
+                npm run test:benchmark:report:odsp;
+                fi
+                if [[ $stage -eq 'frs' ]]; then
+                npm run test:benchmark:report:frs;
+                fi
+                executionTimeTestsExitCode=$?;
+
+                echo "FLUID_ENDPOINTNAME = $FLUID_ENDPOINTNAME"
+                # Run memory tests
+                if [[ $stage -eq 'local' ]]; then
+                npm run test:memory-profiling:report;
+                fi
+                if [[ $stage -eq 'odsp' ]]; then
+                npm run test:memory-profiling:report:odsp;
+                fi
+                if [[ $stage -eq 'frs' ]]; then
+                npm run test:memory-profiling:report:frs;
+                fi
+                memoryTestsExitCode=$?;
+
+                if [[ $executionTimeTestsExitCode -ne 0 ]]; then
+                  echo "##vso[task.logissue type=error]Exit code for runtime tests execution = $executionTimeTestsExitCode ${{ stage }}"
+                fi
+
+                if [[ $memoryTestsExitCode -ne 0 ]]; then
+                  echo "##vso[task.logissue type=error]Exit code for memory tests execution = $memoryTestsExitCode ${{ stage }}"
+                fi
+
+                if [[ $executionTimeTestsExitCode -ne 0 ]] || [[ $memoryTestsExitCode -ne 0 ]]; then
+                  exit 1;
+                fi
+            env:
+              FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
+              FLUID_BUILD_ID: $(Build.BuildId)
+              login__microsoft__clientId: $(login-microsoft-clientId)
+              login__microsoft__secret: $(login-microsoft-secret)
+              login__odsp__test__tenants: $(automation-stress-login-odsp-test-tenants)
+              fluid__test__driver__frs: $(automation-fluid-test-driver-frs-stress-test)
+              FLUID_ENDPOINTNAME: ${{ stage }}
+
+          - task: Bash@3
+            displayName: Write measurements to Aria/Kusto - execution time ${{ stage }}
+            condition: succeededOrFailed()
+            inputs:
+              targetType: 'inline'
+              workingDirectory: $(toolAbsolutePath)
+              script: |
+                echo "Writing the following performance tests results to Aria/Kusto - ${{ stage }}"
+                ls -la ${{ variables.executionTimeTestOutputFolder }};
+                node --require @ff-internal/aria-logger bin/run --handlerModule $(toolAbsolutePath)/dist/handlers/executionTimeTestHandler.js --dir ${{ variables.executionTimeTestOutputFolder }};
+            env:
+              FLUID_ENDPOINTNAME: ${{ stage }}
+
+          - task: Bash@3
+            displayName: Write measurements to Aria/Kusto - memory usage ${{ stage }}
+            condition: succeededOrFailed()
+            inputs:
+              targetType: 'inline'
+              workingDirectory: $(toolAbsolutePath)
+              script: |
+                echo "Writing the following performance tests results to Aria/Kusto - ${{ stage }}"
+                ls -la ${{ variables.memoryUsageTestOutputFolder }};
+                node --require @ff-internal/aria-logger bin/run --handlerModule $(toolAbsolutePath)/dist/handlers/memoryUsageTestHandler.js --dir ${{ variables.memoryUsageTestOutputFolder }};
+            env:
+              FLUID_ENDPOINTNAME: ${{ stage }}
+
+          - task: Bash@3
+            displayName: Send Execution Time Perf Benchmark Measurements to Azure App Insights
+            condition: eq(${{ stage }}, 'local')
+            inputs:
+              targetType: 'inline'
+              workingDirectory: $(toolAbsolutePath)
+              script: |
+                echo "Writing execution time performance benchmark output to Azure App Insights..."
+                ls -laR ${{ variables.executionTimeTestOutputFolder }};
+                node bin/run appInsights --handlerModule $(toolAbsolutePath)/dist/handlers/appInsightsExecutionTimeTestHandler.js --dir '${{ variables.executionTimeTestOutputFolder }}' --connectionString '$(fluid-interal-app-insights-connection-string)';
+            env:
+              BUILD_ID: $(Build.BuildId)
+              BRANCH_NAME: $(Build.SourceBranchName)
+              FLUID_ENDPOINTNAME: ${{ stage }}
+
+          - task: Bash@3
+            displayName: Send Memory Usage Perf Benchmark Measurements to Azure App Insights
+            condition: eq(${{ stage }}, 'local')
+            inputs:
+              targetType: 'inline'
+              workingDirectory: $(toolAbsolutePath)
+              script: |
+                echo "Writing memory usage performance benchmark output to Azure App Insights..."
+                ls -laR ${{ variables.memoryUsageTestOutputFolder }};
+                node bin/run appInsights --handlerModule $(toolAbsolutePath)/dist/handlers/appInsightsMemoryUsageTestHandler.js --dir '${{ variables.memoryUsageTestOutputFolder }}' --connectionString '$(fluid-interal-app-insights-connection-string)';
+            env:
+              BUILD_ID: $(Build.BuildId)
+              BRANCH_NAME: $(Build.SourceBranchName)
+              FLUID_ENDPOINTNAME: ${{ stage }}
+
+          - task: PublishPipelineArtifact@1
+            displayName: Publish Artifact - E2E perf tests output - execution time {{ $stage }}
+            condition: and(succeededOrFailed(), eq(${{ stage }}, 'local'))
+
+            inputs:
+              targetPath: '${{ variables.executionTimeTestOutputFolder }}'
+              artifactName: 'perf-test-outputs-e2e_execution-time'
+
+          - task: PublishPipelineArtifact@1
+            displayName: Publish Artifact - E2E perf tests output - memory usage {{ $stage }}
+            condition: and(succeededOrFailed(), eq(${{ stage }}, 'local'))
+            inputs:
+              targetPath: '${{ variables.memoryUsageTestOutputFolder }}'
+              artifactName: 'perf-test-outputs-e2e_memory-usage'
+
+          - task: Bash@3
+            displayName: Remove Output Folders from local server run ${{ stage }}
+            inputs:
+              targetType: 'inline'
+              workingDirectory: $(toolAbsolutePath)
+              script: |
+                ls -laR ${{ variables.executionTimeTestOutputFolder }};
+                echo "Cleanup  ${{ variables.executionTimeTestOutputFolder }}"
+                rm -rf ${{ variables.executionTimeTestOutputFolder }};
+                ls -laR ${{ variables.memoryUsageTestOutputFolder }};
+                echo "Cleanup  ${{ variables.memoryUsageTestOutputFolder }}"
+                rm -rf ${{ variables.memoryUsageTestOutputFolder }};
